version: '3.8'

services:
  meusuper-app:
    image: node:20-alpine
    networks:
      - MSAppRede 
    working_dir: /app
    volumes:
      - meusuper-data:/app
    command: >
      sh -c "
        apk add --no-cache git &&
        rm -rf /app/* &&
        rm -rf /app/.* 2>/dev/null || true &&
        git clone --depth=1 https://github.com/seu-usuario/meusuper-app.git . &&
        rm -rf .git &&
        npm install --legacy-peer-deps &&
        npm run build &&
        npm run start
      "
    environment:
      # Configuração do Banco de Dados
      - DATABASE_URL=postgresql://neondb_owner:npg_LbGw9i6rWjAB@ep-weathered-cherry-acpldkqj-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
      - PGHOST=ep-weathered-cherry-acpldkqj-pooler.sa-east-1.aws.neon.tech
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_LbGw9i6rWjAB
      - PGDATABASE=neondb
      - PGPORT=5432
      
      # Configuração do Node.js
      - NODE_ENV=production
      - PORT=5000
      
      # Configuração de Sessão
      - SESSION_SECRET=meusuper-app-super-secret-session-key-2025
      
      # Dados do SMTP
      - MAILER_USER=contato@meusuper.app
      - MAILER_PASSWORD=Pj2Nr0BdsfCTRnmM
      - MAILER_HOST=smtp-relay.brevo.com
      - MAILER_PORT=587
      
      # Configuração da Aplicação
      - APP_NAME=MeuSuper.app - Agentes de IA Multicanal
      - APP_URL=https://meusuper.app
      
      # Configuração de CORS
      - ALLOWED_ORIGINS=https://meusuper.app,https://www.meusuper.app
      
      # WhatsApp Integration
      - WHATSAPP_NUMBER=5511999999999
      
      # Webhook Configuration
      - WEBHOOK_URL=https://n8n.meusuper.app/webhook/leads
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.meusuper-main.rule=Host(`meusuper.app`) || Host(`www.meusuper.app`)
        - traefik.http.routers.meusuper-main.entrypoints=websecure
        - traefik.http.routers.meusuper-main.priority=1
        - traefik.http.routers.meusuper-main.service=meusuper-main
        - traefik.http.routers.meusuper-main.tls.certresolver=letsencryptresolver
        - traefik.http.services.meusuper-main.loadbalancer.server.port=5000
        - traefik.http.services.meusuper-main.loadbalancer.passHostHeader=true
        # Redirect www to non-www
        - traefik.http.middlewares.meusuper-redirect.redirectregex.regex=^https://www\.meusuper\.app(.*)
        - traefik.http.middlewares.meusuper-redirect.redirectregex.replacement=https://meusuper.app$${1}
        - traefik.http.routers.meusuper-main.middlewares=meusuper-redirect

volumes:
  meusuper-data:
    external: true
    name: meusuper-data

networks:
  MSAppRede:
    external: true
    name: MSAppRede